name: Validate PR

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, edited]

env:
  BRANCH: ${{ github.ref }}

jobs:
  validate_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repo
        uses: actions/checkout@v2
      - name: execute teste
        run: echo ${{ steps.pr_get_commit_message.outputs.pr_commit_message }}
        
